const COMMON_VALUES = {
  FONT_SIZE_LOW: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_HIGH: 16,
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
  FONT_OPACITY_HIGH: 87,
  FONT_OPACITY_MEDIUM: 65,
  FONT_OPACITY_LOW: 30,
  CONTAINER_PADDING: 20,
  DEFAULT_BORDER: 10,
  TEXT_LINE_SPACE_HIGH: 20,
  ITEM_PADDING: 10,
  BORDER_SIZE: 1,
  FULL: 1,
};

const DARK = {
  ...COMMON_VALUES,
  CONTAINER_COLOR: '#0B0B0C',
  BACKGROUND_COLOR: '#121212',
  BORDER_COLOR: '#696fc5',
  PRIMARY_TEXT_COLOR: '#FFF',
  ICON_COLOR: '#FFF',
};

const LIGHT = {
  ...COMMON_VALUES,
  CONTAINER_COLOR: '#f0f6f7',
  BACKGROUND_COLOR: '#fff0',
  PRIMARY_TEXT_COLOR: '#000',
  ICON_COLOR: '#000',
  BORDER_COLOR: '#0094cc',
};

export { LIGHT, DARK };
